# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Accueil"
  url = "#about"
  weight = 10

[[main]]
  name = "Appel à contributions"
  url = "call-for-papers/"
  weight = 15

#[[main]]
#  name = "Lieu"
#  url = "venue/"
#  weight = 18 

#[[main]]
#  name = "Inscription"
#  url = "registration/"
#  weight = 20

#[[main]]
#  name = "Programme"
#  url = "program/"
#  weight = 30
  
#[[main]]
#  name = " Activités pré-congrès"
#  url = "aligned-events/"
#  weight = 40

#[[main]]
#  name = "Commenditaires"
#  url = "sponsors/"
#  weight = 60


[[main]]
  name = "Contact"
  url = "contact/"
  weight = 60

[[main]]
  name = "English"
  url = "https://cais2026.ca"
  weight = 70

